services:
  ui:
    build: ui
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./ui/src:/app/src
  graphql-server:
    build: graphql-server
    ports:
      - 4000:4000
    volumes:
      - ./graphql-server/src:/server_app/src
